Frito_Restraunt/Frito_Restraunt/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings

from django.views.static import serve
from core.consumer import GetCart , GetCashierItems , my_orders
from product.admin import CustomChartsAdmin
# from product.admin import custom_admin_site
urlpatterns = [
path('admin/', admin.site.urls),
re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
path("",include('home.urls', namespace='home')),
path('core/', include('core.urls', namespace='core')),
path('userauths_api/', include('userauths_api.urls', namespace='userauths_api')),

path('userauths/', include('userauths.urls')),
    path('product/', include('product.urls')),  # Include the product app URLs
    path('custom_charts/', CustomChartsAdmin().custom_charts_view, name='custom_charts'),

    # path('custom_admin/', custom_admin_site.urls),  # Custom admin site URL

]

websocket_route = [
    re_path(r"^cart/$", GetCart.as_asgi()),  # Matches "wss://frito-restraunt.com/cart"
    re_path(r"^core/ws/cart/admin/$", GetCashierItems.as_asgi()),  # Matches "wss://frito-restraunt.com/core/ws/cart/admin/"
    re_path(r"^my_orders/orders/$", my_orders.as_asgi())  # Matches "wss://frito-restraunt.com/my_orders/orders/"
]

Frito_Restraunt/core/urls.py
from django.contrib import admin
from django.urls import include,path
from core.views import (index,product_list,category_list,category_product_list_view,get_product_by_id,get_products_name,AddToCardView,show_card,RemoveFromCardView,wishlist,
                        AddToWishCardView,RemoveFromWishCardView,AddReview,message_socket,offers_product_list_view,add_to_cart,
                        remove_from_Card,checkout,checkout_ajax,user_checked_items,my_orders,place_order,user_ordered_items,save_cashier_table,contact_us)
from .consumer import GetCart,GetCashierItems
from django.urls import re_path
app_name = "core"
urlpatterns = [
path("",include("home.urls", namespace='home')),
path("commentProduct/",AddReview.as_view(),name="commentProduct"),
path('ajax/', checkout_ajax, name='checkout_ajax'),  # URL for the checkout AJAX endpoint

path("wishlist_Add/",AddToWishCardView.as_view(),name="wishlist_Add"),
path('remove_from_wish/', RemoveFromWishCardView.as_view(), name='remove_from_wish'),

path("wishlist/",wishlist,name="wishlist"),

# path('remove_from_card/', RemoveFromCardView.as_view(), name='remove_from_card'),
path('removefromcard/', remove_from_Card, name='remove_from_card'),
path('place_order/', place_order, name='place_order'),
# path('add_to_card/', AddToCardView.as_view(), name='add_to_card'),
path('add-to-cart/', add_to_cart, name='add_to_cart'),
path("show_card/",show_card,name="show_card"),
path("message/",message_socket,name="message"),

path("get_products/<pid>",get_product_by_id,name="get_products"),
path("get_products_name/",get_products_name,name="get_products_name"),
path("products/",product_list,name="product_list"),

path("category/",category_list,name="category_list"),
path("user_checked_items/<user>/",user_checked_items,name="user_checked_items"),

path("category/<cid>/",category_product_list_view,name="category_product_list"),
path("offers/<oid>/",offers_product_list_view,name="offers_product_list_view"),
path('checkout/', checkout,name="checkout"),
path('my_orders/', my_orders,name="my_orders"),
path('user_ordered_items/<user_email>/<int:order_number>/', user_ordered_items,name="user_ordered_items"),
# path('all_useres_ordered/', user_ordered_items,name="user_ordered_items"),

path('save_cashier_table/<int:id>', save_cashier_table, name="save_cashier_table"),
path('contact_us/', contact_us, name="contact_us"),
path('admin/', admin.site.urls),
path("user/",include("userauths.urls")),

]

# websocket_route=[
#     re_path(r'core/ws/cart/$', GetCart.as_asgi()),
#     re_path(r'^core/ws/cart/admin/$', GetCashierItems.as_asgi()),
# ]

Frito_Restraunt/home/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings

from django.views.static import serve
app_name = "home"
from .views import index,login
urlpatterns = [
path('', index,name='home'),
]

Frito_Restraunt/userauths/urls.py
from django.urls import path
from userauths import views


app_name = "userauths"

urlpatterns = [
    path("register", views.register_or_login_user ,name="register"),
    path("login", views.register_or_login_user ,name="login"),
    path("logout", views.logout_view ,name="logout"),
    path("fetch_img", views.fetch_img ,name="fetch_img")
    
]

Frito_Restraunt/templates/Cashier.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

{% endblock content %}

Frito_Restraunt/templates/Login.html
<html>
    {% load static%}
    <head>
        <link rel="stylesheet" href="{% static '/assets/css/bootstrap.min.css' %}">

        <link rel="stylesheet" href="{% static '/assets/css/index.css' %}">
        <link rel="stylesheet" href="{% static '/assets/css/login.css' %}">
        <title>Login Page</title>
        <link rel="icon" type="image/x-icon" href="{% static '/assets/imgs/fr.ico' %}">

        <style>

        </style>
    </head>
    <body >
        <a class="fr_ico_home" href="{% url 'home:home' %}">
            <!-- <div class="fr_ico_home"></div> -->

    </a>
        <div style="height:200px;  margin-left: 10%;">
            <div class="left-image"></div>
            <div class="right-image"></div>
        </div>


      
    <div id="errors" data-errors='{"error_account":"{{ error_account }}","error_password": "{{ error_password }}"}'></div>
    <div id="alert-container" style="position: fixed; top: 20px; right: 20px; z-index: 1050;"></div>
    
        <div class="flip-card-inner " style="height: 25%; width: 200%;  margin-top: -20%; margin-left: -20%;">

          <div class="flip-card-front" style="margin-top: 50%; ">

            <form action="{% url 'userauths:login' %}" id="Login_Form" method="POST">
                <div class="flip-card center-content" style=" top: -450%; width: 55%; height: 400%;   background-color: rgba(0, 0, 0, 0.5); justify-content: center; flex-direction: column; border-radius: 20%;   ">

                    <div style="height: 20px;"></div>
                    <img src="{% static 'assets/imgs/S.png' %}" width="300px" height="300px" id="Login_img" style=" margin-left: 0%;  border-radius: 100%; " alt="Cinque Terre">
                    <div style="height: 5%;">
            </div>
                {% csrf_token %}

            <div class="row" style="display: flex; align-items: center; margin-bottom: 15px;">
                <div class="col-1"></div>
                <div class="text-center" style="margin-right: 5px;">
                    <p style="color: white; margin: 0; font-size: xx-large;">Account&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp;</p>
                </div>
                <div style="margin-right: 5px;">
                    <p style="color: red; margin: 0;">*</p>
                </div>
                <div style="flex-grow: 1; position: relative;">
                    <input type="email" name="email" id="email" style=" height: 50px;  background-color: white; border: 1px solid aqua; width: 98%; margin-right: 70%; box-sizing: border-box; color: black;  " placeholder="Your Account">
                </div>
                <div class="col-1"></div>
            </div>
            <div style="height: 15px;"></div>
            <div class="row" style="display: flex; align-items: center;">

                <div class="col-1"></div>
                <div class="text-center" style="margin-right: 5px;">
                    <p style="color: white; margin: 0; font-size: xx-large;">Password&nbsp;:&nbsp;</p>
                </div>
                <div style="margin-right: 5px;">
                    <p style="color: red; margin: 0;">*</p>
                </div>
                <div style="flex-grow: 1; position: relative;">
                    <input type="password" name="password" id="password" style=" height: 50px;  background-color: white; border: 1px solid aqua; width: 98%; margin-right: 70%; box-sizing: border-box; color: black;" placeholder="Your Password">
                </div>
                <div class="col-1"></div>
            </div>
            <div style="height: 10px;"></div>
            <div class="row" style="display: flex; justify-content: center; align-items: center;">
                <div style="width: 15px;"></div>
                <button type="button" id="Login_Flip_Card" class="SignUp" style="width: 40%; height: 10%;">Register</button>

                <div style="flex-grow: 0; width: 3ch;"></div>
                
                <button type="submit" class="SignUp_login" id="login_submit_button" style="width: 40%; height: 10%;"  name="action" value="Login">Login</button>
                
                <div class="col-1"></div>
            </div>
            </div>
            </form>
        </div>




    <div class="flip-card-back"  style="margin-top: 50%;">
        <form method="POST" action="{% url 'userauths:register' %}" enctype="multipart/form-data" id="Register_Form">
            {% csrf_token %}
            <div class="flip-card center-content" style=" top: -450%; width: 55%; height: 400%;   background-color: rgba(0, 0, 0, 0.5); justify-content: center; flex-direction: column; border-radius: 20%;   ">

            <div class="flip-card-inner">
              <div class="flip-card-front">
    
            <div style="height: 20px;"></div>
         
            <label for="profile_picture" style="position: relative; pointer-events: none;">
                <img src="{% static 'assets/imgs/S.png' %}" id="upload_register_photo" width="300px" height="300px" style=" margin-left: 0%;  border-radius: 100%; " alt="Cinque Terre">
                <input type="file" name="profile_picture" id="profile_picture" style="position: absolute; display: none;">
              </label>
            
            

            <div style="height: 5%;">
    </div>


    <div class="row" style="display: flex; align-items: center; margin-bottom: 15px;">
        <div class="col-1"></div>
        <div class="text-center" style="margin-right: 5px;">
            <p style="color: white; margin: 0; font-size: xx-large;">UserName&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
        <div style="margin-right: 5px;">
            <p style="color: red; margin: 0;">*</p>
        </div>
        <div style="flex-grow: 1; position: relative;">
            {{form.username}}
        </div>
        <div class="col-1"></div>
    </div>
    <div class="row" style="display: flex; align-items: center; margin-bottom: 15px;">
        <div class="col-1"></div>
        <div class="text-center" style="margin-right: 5px;">
            <p style="color: white; margin: 0; font-size: xx-large;">Account&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
        <div style="margin-right: 5px;">
            <p style="color: red; margin: 0;">*</p>
        </div>
        <div style="flex-grow: 1; position: relative;">
            {{form.email}}
        </div>
        <div class="col-1"></div>
    </div>
    <div style="height: 15px;"></div>


    <div class="row" style="display: flex; align-items: center; margin-bottom: 15px;">
        <div class="col-1"></div>
        <div class="text-center" style="margin-right: 5px;">
            <p style="color: white; margin: 0; font-size: xx-large;">Password&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
        <div style="margin-right: 5px;">
            <p style="color: red; margin: 0;">*</p>
        </div>
        <div style="flex-grow: 1; position: relative;">
            {{form.password1}}
        </div>
        <div class="col-1"></div>
    </div>












    <div style="height: 15px;"></div>

    <div class="row" style="display: flex; align-items: center;">
    
        <div class="col-1"></div>
        <div class="text-center" style="margin-right: 5px;">
            <p style="color: white; margin: 0; font-size: xx-large;">Confirm Password&nbsp;:&nbsp;</p>
        </div>
        <div style="margin-right: 5px;">
            <p style="color: red; margin: 0;">*</p>
        </div>
        <div style="flex-grow: 1; position: relative;">

            {{form.password2}}
            
        </div>
        <div class="col-1"></div>
    </div>
    <div style="height: 10px;"></div>
    

    
    <div class="row" style="display: flex; justify-content: center; align-items: center;">
        <button type="submit" class="SignUp" name="action" value="Register">Register</button>
        <div style="margin: 0 10px;"></div>
        <button class="SignUp_login" id="Flib_Back_To_Login">Back To Login</button>
    </div>
    
    
    
    
    
        </div>
    

</div>
















      </div>
    </form>

      </div>
      </div>
  
      </div>

    
      <script>
        var btn = document.getElementById("Login_Flip_Card");
        var card = document.querySelector(".flip-card-inner");
        var btn2 = document.getElementById("Flib_Back_To_Login");

        btn.addEventListener("click", function() {
          card.classList.toggle("flipped");
        });
        btn2.addEventListener("click", function() {
          card.classList.toggle("flipped");
        });
        </script>


    <!-- <script src="{% static 'assets/js/jquery-3.5.1.slim.min.js' %}"></script> -->
    <script src="{% static 'assets/js/jquery-3.7.1.min.js' %}"></script>

    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/register.js' %}"></script>
    <script src="{% static 'assets/js/get_img_ajax.js' %}"></script>
    <script src="{% static 'assets/js/errors_registeration_or_login.js' %}"></script>
    </body>
    </html>
    

Frito_Restraunt/templates/MyOrders.html
<!-- templates/MyOrders.html -->

{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Your Ordered Items</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Order Number</th>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Meal Type</th>
                <th>Meal Side Dishes</th>
                <th>Meal Additions</th>
                <th>Client Status</th>
            </tr>
        </thead>
        <tbody>
            {% for item in user_ordered_items %}
            <tr>
                <td>{{ item.order_number }}</td>
                <td>{{ item.uoc_prod.title }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.total_price_for_all }} L.E</td>
                <td>{{ item.user_meal_type }}</td>
                <td>
                    {% for dish in item.MealSideDishes %}
                        {% for key, value in dish.items %}
                            {% if key != 'side_image' %}
                                {{ key }}: {{ value }}
                            {% endif %}
                        {% endfor %}
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                
                <td>
                    {% for addition in item.MealAdditions %}
                        {% for key, value in addition.items %}
                            {% if key != 'addition_image' %}
                                {{ key }}: {{ value }}
                            {% endif %}
                        {% endfor %}
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
                                <td>{{ item.cashier_table.client_status }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="8">No items found.</td>
            </tr>
            {% endfor %}
            
        </tbody>
    </table>


</div>
{% if total_price %}  
<div style=" margin-left: 220px; background-color: cyan; width: 100vw; height: 100px; display: flex; justify-content: center; align-items: center;">
    <h5 style="font-weight: bold; color: black; margin: 0;">
        Total Price: <span id="Subtotal_mini_card" style="color: red;">{{ total_price }} L.E</span>
    </h5>
</div>

{% endif %}
{% endblock content %}

Frito_Restraunt/templates/contact_us.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<style>
     .content_all {
        display: flex;
        justify-content: space-between;
    }

    .restaurant-info {
        width: 45%; /* Adjust width as needed */
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
    }

    #map {
        width: 50%; /* Adjust width as needed */
        height: 400px;
        border-radius: 8px;
        overflow: hidden;
    }

    .restaurant-info h2 {
        font-size: 24px;
        margin-bottom: 10px;
    }

    .restaurant-info p {
        margin-bottom: 10px;
        line-height: 1.6;
    }
</style>
<link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />

<div class="content_all">
    <div class="restaurant-info">
        <h2>Frito Restaurant</h2>
        <p><strong>Address:</strong> 197 on Hours Gate at Hdaek El-Ahram</p>
        <p><strong>Telephone:</strong> 01028440208, 01070124774</p>
        <p><strong>Facebook:</strong> <a href="http://www.facebook.com/frito.friedchicken" target="_blank">www.facebook.com/frito.friedchicken</a></p>
    </div>

    <div id="map"></div>
</div>

<!-- Leaflet JavaScript -->
<script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    var map = L.map('map').setView([29.9492149, 31.0950911], 15);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    var customIcon = L.icon({
        iconUrl: '{% static 'assets/imgs/red_marker.png' %}', // Replace with correct path to your marker icon
        iconSize: [25, 41], // Size of the icon
        iconAnchor: [12, 41], // Point of the icon which corresponds to marker's location
        popupAnchor: [1, -34] // Point from which the popup should open relative to the iconAnchor
    });

    var marker = L.marker([29.9492149, 31.0950911], { icon: customIcon }).addTo(map)
        .bindPopup('<b>Frito Restaurant</b><br>197 on Hours Gate at Hdaek El-Ahram')
        .openPopup();
});

</script>
{% endblock content %}

Frito_Restraunt/templates/index33.html
<!DOCTYPE html>
<html>
    {% load static %}
<head>
    <title>Frito Restaurant</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'assets/imgs/fr.ico' %}">
    <link rel="stylesheet" href="{% static 'assets/css/index.css' %}">
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .nav-container {
            display: flex;
            align-items: center;
        }

        .hamburger {
            cursor: pointer;
            margin-right: 20px;
        }

        .hamburger div {
            width: 25px;
            height: 3px;
            background-color: #333;
            margin: 5px 0;
        }

        .horizontal {
            list-style: none;
            padding: 0;
            margin: 0;
            display: flex;
            align-items: center;
        }

        .horizontal li {
            margin: 0 15px;
        }

        .horizontal a {
            text-decoration: none;
            color: #333;
        }

        .vertical-nav {
            display: none;
            position: absolute;
            top: 50px;
            left: 0;
            background-color: white;
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
            width: 200px;
            z-index: 1000;
        }

        .vertical-nav ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        .vertical-nav li {
            padding: 10px;
        }

        .vertical-nav a {
            text-decoration: none;
            color: #333;
            display: flex;
            align-items: center;
        }

        .vertical-nav img {
            width: 20px;
            height: 20px;
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <!-- Head -->
    <div>
        <img src="{% static 'assets/imgs/Frito-noBackgroundpreview.png' %}" height="85px" width="180px" style="float: left; margin-top: 10px;">
        <div style="margin-top: 45px; float: left;">
            <form>
                <div style="display: flex; margin-left: 150px;">
                    <select class="form-control amazing-font tight-bond listoption" style="font-size: 14px; width: 200px; height: 40px;">
                        <option value="default" class="listoption" selected>DEFAULT</option>
                        <option value="one" class="listoption">One: All Categories</option>
                        <option value="two" class="listoption">Two: All Categories</option>
                        <option value="three" class="listoption">Three: All Categories</option>
                    </select>
                    <input type="text" class="search_input" placeholder="  Search For Anything You Like...">
                    <button type="button" class="searchbutton">Search</button>
                </div>
            </form>
        </div>
        <div style="float: left; margin-left: 150px; margin-top: 45px; margin-right: 2px;">
            <div style="color: red;">
                <!-- Wishlist -->
                <a href="#" class="Wish_And_Card">
                    <div class="card-container" id="MyCard">
                        <img src="{% static 'assets/imgs/shopwishlist.png' %}" width="50px" height="50px">
                        <!-- <span class="product-count">0</span> -->
                    </div>
                    Wishlist
                </a>
                <!-- Card -->
                <a href="#" class="Wish_And_Card">
                    <div class="card-container" id="MyWishlist">
                        <img src="{% static 'assets/imgs/ShopCard2.png' %}" width="50px" height="50px">
                        <!-- <span class="product-count">0</span> -->
                    </div>
                    Card
                </a>
                <!-- Account -->
                {% if user.is_authenticated %}
                <a href="{% url 'userauths:logout' %}" class="Auth">
                    <img src="{{ prof_img }}" width="50px" height="50px">
                    Logout
                </a>
                {% else %}
                <a href="{% url 'userauths:register' %}" class="Auth">
                    <img src="{% static 'assets/imgs/pers.png' %}" width="50px" height="50px">
                    Login
                </a>
                {% endif %}
            </div>
        </div>
    </div>
    <div style="height: 50px;"></div>
    <div>
        <div class="nav-container">
            <div class="hamburger" id="hamburger">
                <div></div>
                <div></div>
                <div></div>
            </div>
            <ul class="horizontal" id="nav">
                <li><a href="#" class="active">Home</a></li>
                <li><a href="#">Our Products</a></li>
                <li><a href="#">FAQs</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div>
        <div class="vertical-nav" id="verticalNav">
            <ul>
                <li class="parent">
                    <a href="#"><img src="{% static 'assets/imgs/parent1.jpg' %}" alt="Parent 1">Parent 1</a>
                    <ul>
                        <li><a href="#"><img src="{% static 'assets/imgs/child1.jpg' %}" alt="Child 1">Child 1</a></li>
                        <li><a href="#"><img src="{% static 'assets/imgs/child2.jpg' %}" alt="Child 2">Child 2</a></li>
                        <li><a href="#"><img src="{% static 'assets/imgs/child3.jpg' %}" alt="Child 3">Child 3</a></li>
                    </ul>
                </li>
                <li class="parent">
                    <a href="#"><img src="{% static 'assets/imgs/parent2.jpg' %}" alt="Parent 2">Parent 2</a>
                    <ul>
                        <li><a href="#"><img src="{% static 'assets/imgs/child1.jpg' %}" alt="Child 1">Child 1</a></li>
                        <li><a href="#"><img src="{% static 'assets/imgs/child2.jpg' %}" alt="Child 2">Child 2</a></li>
                        <li><a href="#"><img src="{% static 'assets/imgs/child3.jpg' %}" alt="Child 3">Child 3</a></li>
                    </ul>
                </li>
                <li class="parent">
                    <a href="#"><img src="{% static 'assets/imgs/parent3.jpg' %}" alt="Parent 3">Parent 3</a>
                    <ul>
                        <li><a href="#"><img src="{% static 'assets/imgs/child1.jpg' %}" alt="Child 1">Child 1</a></li>
                        <li><a href="#"><img src="{% static 'assets/imgs/child2.jpg' %}" alt="Child 2">Child 2</a></li>
                        <li><a href="#"><img src="{% static 'assets/imgs/child3.jpg' %}" alt="Child 3">Child 3</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const hamburger = document.getElementById('hamburger');
            const verticalNav = document.getElementById('verticalNav');

            hamburger.addEventListener('click', () => {
                verticalNav.style.display = verticalNav.style.display === 'block' ? 'none' : 'block';
            });
        });
    </script>
    <script src="{% static 'assets/js/jquery-3.5.1.slim.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
</body>
</html>

Frito_Restraunt/templates/user_ordered_items.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

<div class="fix_me" style="flex: 1; overflow-x: auto;">
    <table class="table table-hover" style="width: 100%;"id="dynamicTable"> <!-- Increased the table width by 1000px -->
        <thead>
            <tr>
                <th style="width: auto">Product Image</th> <!-- Increased the width by 1000px -->
                <th style="width: auto;">Product Name</th> <!-- Increased the width by 1000px -->

                <th style="width: auto;">Product Meal Offer</th> <!-- Increased the width by 1000px -->
                <th style="width: auto;">Product Meal Type</th> <!-- Increased the width by 1000px -->
                <th style="width: auto;">Product Side Dishes</th> <!-- Increased the width by 1000px -->
                <th style="width: auto;">Product Additions Type</th> <!-- Increased the width by 1000px -->
                <th style="width: auto;">Product Total Price</th> <!-- Increased the width by 1000px -->
            </tr>
        </thead>
        <tbody>
             {% if my_ordered_items %}
            {% for i in my_ordered_items %}
            <tr>
                <td>
                     <div style="background-image: url('{{ i.uoc_prod.image.url }}'); width: 100px; height: 100px; background-size: cover; background-color: transparent;"></div>
                </td>
                <td>{{ i.uoc_prod.title }}</td>
                {% if i.user_meal_type == "Default" %}
                <td>{{ i.user_meal_type }} and quantity is {{ i.quantity }} </td>
                <td>{{ i.MealType }}</td>
                <td>{{ i.MealSideDishes }}</td>
                <td>{{ i.MealAdditions }}</td>
                <td>{{ i.total_price_for_all }} L.E</td>

                {% else %}
                <td>
                Special
                </td>
                <td>
                    [
                    {% for p in i.MealType %}
                    {
                        'Meal Type': '{{ p.product_meal_type }}',
                        'quantity': '{{ p.quantity }}'
                    }{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    ]
                </td>
                <td>
                    [
                    {% for p in i.MealSideDishes %}
                    {
                        'Meal Type': '{{ p.product_side_dish }}',
                        'quantity': '{{ p.quantity }}'
                    }{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    ]
                </td>
                <td>
                    [
                    {% for p in i.MealAdditions %}
                    {
                        'Meal Type': '{{ p.additionName }}',
                        'quantity': '{{ p.quantity }}'
                    }{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                    ]
                </td>
                <td>{{ i.total_price_for_all }} L.E</td>


                 {% endif %}

            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            {% endif %}
            
            <!-- Additional rows here -->
           
        </tbody> 
        
    </table>
    
    <div style="align-content: center; background-color: #ccc;">
        {% if total_price %}

        <h1  style="text-align: center;">Total Price: <span style="display: inline; color: red;" id="Subtotal_table">{{ total_price }} L.E</span></h1>
        {% else %}
        <h1 style="text-align: center;">Total Price: <span style="display: inline; color: green;">FREE</span></h1>



        {% endif %}
     </div>
</div>
{% endblock content %}